config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => 'session#index'

  resources :session, only: [:index, :show]
  
  post 'session/create'
  get  'restaurant/index'
  post 'restaurant/create'
  post 'voter/create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :voters, dependent: :delete_all
  belongs_to :session

end

app/models/session.rb
class Session < ApplicationRecord
  has_many :restaurants, dependent: :delete_all

end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :restaurant

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController

  def create
    @restaurant = Restaurant.create(
      name:  params[:name],
      address: params[:vicinity],
      rating: params[:rating],
      google_place_id: params[:place_id],
      session_id: params[:session_id]
    )
    redirect_to session_path(params[:session_id])
  end 

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def index
  end

  def create
    @session = Session.create
    redirect_to session_path(@session)
  end

  def show
    @session = Session.find(params[:id])
    @restaurants_list = call_nearbysearch_google_api(params[:latitude], params[:longitude])
    @restaurants = @session.restaurants
  end

  private 

  def call_nearbysearch_google_api(latitude, longitude)
    url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{latitude}%2C#{longitude}&radius=1000&type=restaurant&key=#{ENV['GOOGLE_API_KEY']}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url)
    response = https.request(request)
    JSON.parse(response.read_body)["results"]
  end

end

app/controllers/voter_controller.rb
class VoterController < ApplicationController

  def create
    @voter = Voter.create(
      restaurant_id: params[:restaurant_id]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/voter_helper.rb
module VoterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteRestaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurant/index.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=<%=ENV['GOOGLE_API_KEY']%>&libraries=places"></script>

<script>
  google.maps.event.addDomListener(window, 'load', initialize);
  function initialize() {
    var input = document.getElementById('address');
    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.addListener('place_changed', function () {
      var place = autocomplete.getPlace();
      document.getElementById("latitude").value = place.geometry['location'].lat();
      document.getElementById("longitude").value = place.geometry['location'].lng();
    });
  }
</script>
  
<div>
  <div>
    <h3>Choisir un lieu pour lister les restaurants à proximité</h3>
    <input id="address"/>
    <%= form_with url: 'restaurant', method: :get do |f| %>
      <%= f.hidden_field:latitude, id: :latitude %>
      <%= f.hidden_field:longitude, id: :longitude %>
      <%= button_tag "Lister les restaurants"%> 
    <% end %>
  </div>
  <% if @restaurants_list.present? %>
    <div>
      <h3>Choisir le ou les restaurants de votre choix</h3>
      <ul>
        <% @restaurants_list.each do |restaurant| %> 
          <li>
            <%= restaurant["name"]%>
            <%= restaurant["vicinity"]%>
            <%= "note: #{restaurant["rating"]}"%>
            <%= button_to "+", restaurant_create_path(restaurant)%>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @restaurants.present? %>
    <div>
      <h3>Voter le ou les restaurants de votre choix</h3>
        <ul>
          <% @restaurants.each do |restaurant| %> 
            <% vote_count = restaurant.voters.count %>
            <div data-controller="vote" data-vote-count-value=<%= vote_count %>>
              <li>
                <%= restaurant.name%>
                <%= restaurant.address%>
                <%= "note: #{restaurant.rating}"%>
                <div data-action="click->vote#increment"><%= button_to "vote +", voter_create_path(restaurant), params: { restaurant_id: restaurant.id }%></div>
              </li>
              <u>Nombre de vote:</u>
              <div data-vote-target="results"></div>     
            </div>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>
 

app/views/session/index.html.erb
<%= button_to "Démarrer une session de vote de restaurant", session_create_path%>

app/views/session/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=<%=ENV['GOOGLE_API_KEY']%>&libraries=places"></script>

<script>
  google.maps.event.addDomListener(window, 'load', initialize);
  function initialize() {
    var input = document.getElementById('address');
    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.addListener('place_changed', function () {
      var place = autocomplete.getPlace();
      document.getElementById("latitude").value = place.geometry['location'].lat();
      document.getElementById("longitude").value = place.geometry['location'].lng();
    });
  }
</script>
  
<div>
  <div>
    <h3>Choisir un lieu pour lister les restaurants à proximité</h3>
    <input id="address"/>
    <%= form_with url: "#{@session.id}", method: :get do |f| %>
      <%= f.hidden_field:latitude, id: :latitude %>
      <%= f.hidden_field:longitude, id: :longitude %>
      <%= button_tag "Lister les restaurants"%> 
    <% end %>
  </div>
  <% if @restaurants_list.present? %>
    <div>
      <h3>Choisir le ou les restaurants de votre choix</h3>
      <ul>
        <% @restaurants_list.each do |restaurant| %> 
          <li>
            <%= restaurant["name"]%>
            <%= restaurant["vicinity"]%>
            <%= "note: #{restaurant["rating"]}"%>
            <%= button_to "+", restaurant_create_path(restaurant), params: { session_id: @session.id }%>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @restaurants.present? %>
    <div>
      <h3>Voter le ou les restaurants de votre choix</h3>
        <ul>
          <% @restaurants.each do |restaurant| %> 
            <% vote_count = restaurant.voters.count %>
            <div data-controller="vote" data-vote-count-value=<%= vote_count %>>
              <li>
                <%= restaurant.name%>
                <%= restaurant.address%>
                <%= "note: #{restaurant.rating}"%>
                <div data-action="click->vote#increment"><%= button_to "vote +", voter_create_path, params: { restaurant_id: restaurant.id }%></div>
              </li>
              <u>Nombre de vote:</u>
              <div data-vote-target="results"></div>     
            </div>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>
 